### ISSUE TITLE
Placing jQuery Script in the head instead of body

### ISSUE THREAD

**Issue by bsoetarto7** [KC74/project_instanews#1]
The jQuery script was placed in the `head` of the `html` instead of the`body`. The jQuery script should be loaded last at the end of the page, just before `</body>`.

This is where you placed the jQuery script
![issue1](https://user-images.githubusercontent.com/6547713/28700563-5b5e51e8-7305-11e7-8961-71d99c9a5b7d.png)

It should be placed before `</body>` on top of the scripts loaded
![issue2](https://user-images.githubusercontent.com/6547713/28700595-97d86c9e-7305-11e7-9e82-24139395fb3b.png)

**Comment by KC74** [comment]
Fixed
